# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main  # ✅ Trigger pipeline on main branch

pool:
  vmImage: 'ubuntu-latest'  # ✅ Correct indentation

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.x'  # ✅ Specify .NET version

  - script: dotnet build --configuration Release
    displayName: 'Build project'

  - script: dotnet test --configuration Release
    displayName: 'Run tests'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'bin/Release'
      artifactName: 'drop'
