# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build application
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: my-build-artifacts
          path: bin/Release
